
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int END = 16;
  public static final int LPAREN = 7;
  public static final int LBRACKET = 9;
  public static final int ID = 18;
  public static final int RBRACKET = 10;
  public static final int DO = 15;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int FOR = 13;
  public static final int TO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "ASSIGN",
  "PRINT",
  "FOR",
  "TO",
  "DO",
  "END",
  "NUMBER",
  "ID"
  };
}

